name: HCL DevOps Test UI

on: workflow_dispatch

jobs:
    UI-Action:
        runs-on: self-hosted
        name: HCL DevOps Test UI
        steps:
         - name: Execute Test
           uses: LekyaS/-devops-test-ui-action@Test
           with:
            projectDirectory:  C:\Users\preethi.as\HCL\devopstest\workspace\Project1
            scriptName: Script1
