name: HCL DevOps Test UI

on: workflow_dispatch

jobs:
    UI-Action:
        runs-on: self-hosted
        name: HCL DevOps Test UI
        steps:
         - name: Execute Test
           uses: LekyaS/-devops-test-ui-action@Test
           with:
            projectDirectory:  D:\Workspace-2024\Project1
            scriptName: Script2
