name: Rational Functional Tester - UI Test

on: workflow_dispatch

jobs:
    Performance-Action:
        name: TestHCL OneTest WebUI GitHub Action
        runs-on: self-hosted
        steps:
         - name: HCL OneTest WebUI GitHub Action
           uses: HCL-TECH-SOFTWARE/onetest-web-action@v1
           with:
            workspace: C:\Users\preethi.as\HCL\devopstest\workspace
            project: webui
            suite: test1
