name: Rational Functional Tester - UI Test

on: workflow_dispatch

jobs:
    Performance-Action:
        name: TestHCL OneTest WebUI GitHub Action
        runs-on: self-hosted
        steps:
         - name: HCL OneTest UI GitHub Action
           uses: HCL-TECH-SOFTWARE/onetest-ui-action@v1
           with:
            projectDirectory:  C:\Users\preethi.as\HCL\devopstest\workspace\Project1    
            scriptName: Script1
