name: HCL OneTest UI

on: workflow_dispatch

jobs:
    UI-Action:
        runs-on: self-hosted
        name: HCL OneTest UI
        steps:
         - name: Execute Test
           uses: HCL-TECH-SOFTWARE/onetest-ui-action@v1
           with:
            projectDirectory:  C:\Users\preethi.as\IBM\devopstest\workspace\Project1
            scriptName: Script2
